# Generated by Django 3.1.1 on 2020-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header_secondary_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_main_header', models.CharField(max_length=350, verbose_name='Secondary Main headline')),
            ],
        ),
        migrations.CreateModel(
            name='header_title_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(max_length=350, verbose_name='Main headline')),
            ],
        ),
        migrations.CreateModel(
            name='home_page_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='', verbose_name='Home Banner Image')),
            ],
        ),
        migrations.CreateModel(
            name='sub_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_header', models.CharField(max_length=350, verbose_name='Sub Title')),
            ],
        ),
    ]
