# Generated by Django 3.1.6 on 2021-02-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_banner',
            name='activate_shareble_link',
            field=models.BooleanField(default=False, verbose_name='Activate Shareable Link'),
        ),
        migrations.AddField(
            model_name='home_page_banner',
            name='img_as_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image As link'),
        ),
    ]
