# Generated by Django 3.1.1 on 2020-09-14 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20200914_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 13, 51, 49, 32348, tzinfo=utc), verbose_name='Created At'),
        ),
    ]
