# Generated by Django 3.1.1 on 2020-09-14 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20200914_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 14, 43, 25, 896476, tzinfo=utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course_offers',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
