# Generated by Django 3.1.6 on 2021-02-05 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0016_auto_20201124_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail_as_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Course's thumbnail as link"),
        ),
        migrations.AddField(
            model_name='course_promo',
            name='activate_shareable_link',
            field=models.BooleanField(default=False, verbose_name='Activate Shareable Link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 16, 2, 6, 872535, tzinfo=utc), verbose_name='Created At'),
        ),
    ]
