# Generated by Django 3.1.1 on 2020-09-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20200914_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_purchased_courses',
        ),
    ]
