# Generated by Django 3.1.1 on 2020-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20200914_1351'),
        ('Accounts', '0007_user_purchased_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchased_courses',
            field=models.ManyToManyField(related_name='new_relation', related_query_name='new_ha', to='Course.Course', verbose_name='Purchased Courses'),
        ),
    ]
