# Generated by Django 3.1.1 on 2020-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_auto_20200914_1701'),
        ('Accounts', '0010_remove_user_user_purchased_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_purchased_courses',
            field=models.ManyToManyField(to='Course.Course'),
        ),
    ]
