# Generated by Django 3.1.1 on 2020-09-20 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20200919_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 17, 47, 46, 356955, tzinfo=utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='courses_video',
            name='video',
            field=models.CharField(default='Lecture.mp4', max_length=3500, verbose_name='Video Name'),
        ),
    ]
