# Generated by Django 3.1.1 on 2020-11-24 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_auto_20200920_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(null=True, to='Course.Courses_Video', verbose_name='Course Content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 21, 37, 55, 343075, tzinfo=utc), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube_content',
            field=models.ManyToManyField(null=True, to='Course.Courses_video_link', verbose_name='Youtube Optional Content Upload'),
        ),
    ]
