# Generated by Django 3.1.1 on 2020-11-24 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_auto_20201124_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_linked',
            field=models.BooleanField(default=True, verbose_name='activate shareable link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 22, 4, 43, 257996, tzinfo=utc), verbose_name='Created At'),
        ),
    ]
